spring:
  config:
    import: file:/run/secrets/db.properties
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
logging:
  level:
    com.nickesqueda: INFO
    org.springframework: INFO
    org.springframework.security: INFO