spring:
  datasource:
    # TODO: extract into secret management solution
    url: jdbc:mysql://localhost:3306/social_media_demo_db?useSSL=false&serverTimezone=UTC
    username: nick
    password: ASDFlkj1234!@#$
  jpa:
    hibernate:
      ddl-auto: update # should be "validate" for PROD
    show-sql: false

logging:
  level:
    com.nickesqueda: INFO
    org.springframework.security: INFO