spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social-media-demo-db?useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update # should be "validate" for PROD
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG